title: Fanny Rebiffé
description: Data scientist
logo: /img/avatar.PNG
theme: jekyll-theme-minimal
show_downloads: false
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
